Traceback (most recent call last):
  File "/h/u2/csc369h/fall/pub/a1b-testing/test.py", line 25, in run_test
    test_function(submission, log)
  File "/h/u2/csc369h/fall/pub/a1b-testing/tests.py", line 150, in test
    s.mount()
  File "/h/u2/csc369h/fall/pub/a1b-testing/submission.py", line 179, in mount
    os.mkdir(self.mnt_path)
FileExistsError: [Errno 17] File exists: '/tmp/_testmnt_'

